[versions]
agp = "8.7.2"
audienceNetworkSdk = "6.21.0"
firebaseBomVersion = "33.5.1"
inmobiAdsKotlin = "10.8.8"
kotlin = "2.1.20"
kotlinxCoroutinesAndroid = "1.7.3"
ksp = "2.1.20-1.0.31"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.9.3"
composeBom = "2024.12.01"
mediationsdk = "9.1.0"
navigationCompose = "2.8.4"
hiltNavigationCompose = "1.2.0"
playServicesAds = "24.7.0"
publisherSdkAndroid = "7.6.0"
vungle = "7.6.0.0"
hilt = "2.56.1"
firebaseBom = "34.6.0"
googleService = "4.4.4"
googleCrashlytics = "3.0.6"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
playServicesAdsIdentifier = "18.2.0"
ironSourceMediationAdapter = "9.1.0.0"
metaMediationAdapter = "6.21.0.0"
inMobiMediationAdapter = "10.8.8.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
audience-network-sdk = { module = "com.facebook.android:audience-network-sdk", version.ref = "audienceNetworkSdk" }
firebase-bom-v3351 = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBomVersion" }
google-firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
inmobi-ads-kotlin = { module = "com.inmobi.sdk:inmobi-ads-kotlin", version.ref = "inmobiAdsKotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

# Charts
kotlinx-coroutines-android-v173 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
mediationsdk = { module = "com.ironsource.sdk:mediationsdk", version.ref = "mediationsdk" }
play-services-ads-v2460 = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }

firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-config-ktx = { module = "com.google.firebase:firebase-config-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
play-services-ads-identifier = { group = "com.google.android.gms", name = "play-services-ads-identifier", version.ref = "playServicesAdsIdentifier" }
ironsource-mediation-adapter = { group = "com.google.ads.mediation", name = "ironsource", version.ref = "ironSourceMediationAdapter" }
meta-mediation-adapter = { group = "com.google.ads.mediation", name = "facebook", version.ref = "metaMediationAdapter" }
inmobi-mediation-adapter = { group = "com.google.ads.mediation", name = "inmobi", version.ref = "inMobiMediationAdapter" }
publisher-sdk-android = { module = "com.vungle:publisher-sdk-android", version.ref = "publisherSdkAndroid" }
vungle = { module = "com.google.ads.mediation:vungle", version.ref = "vungle" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
# THAY ĐỔI: Thêm plugin Google Services và Crashlytics Gradle
google-services = { id = "com.google.gms.google-services", version.ref = "googleService" }
google-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "googleCrashlytics" }